# Simple deployment used to deploy and manage the app in qhung1412/gsk8s:v1
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deploy
  labels:
    app: web
spec:
  replicas: 9
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec: 
      terminationGracePeriodSeconds: 1
      containers:
      - name: hello-pod
        image: qhung1412/gsk8s:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 8080