# Simple Kubernetes Pod to deploy the app contained in qhung1412/gsk8s:v1
apiVersion: v1
kind: Pod
metadata:
  name: hello-pod
  labels:
    app: web
spec:
  containers:
    - name: web-ctr
      image: qhung1412/gsk8s:v1
      ports:
        - containerPort: 8080
